main:
  - name: Bio
    url: /
    weight: 10
  - name: Research Publications
    url: /#papers
    weight: 20
  - name: Research Areas
    url: /#research-areas
    weight: 30
  - name: Awards & Recognition
    url: /#awards
    weight: 40
  - name: Education
    url: experience/
    weight: 50
  - name: Contact
    url: /#contact
    weight: 60
